name : Foundation5/github pages/Jykill starter
brand : KevinOh 
description : Kevin Oh. Web Designer & Developer
keyword : 
url : http://daigofuji.github.io/jekyll-foundation-5-starter/
email : daigo@daigofujiwara.com
twitter : DaigoFuji
github : DaigoFuji
author : Daigo Fujiwara
analytics : UA-8418273-8
year : 2015
markdown : kramdown
